print("\"The stars are bright\".")
print("\"The stream bubbles\".")
print("\"The wind whistles\".")
print("\"What a wonderful night\". The man wrote into his journal.")
print("\"The only thing that could make it better is if I was at home to enjoy it.\" Wrote the man wistfully.")
